[package]
name = "date-version"
version = "0.1.0"
authors = ["Conor Patrick <conor@solokeys.com>"]
edition = "2018"

[[bin]]
name = "date-version"

[dependencies]
anyhow = "1"
clap = "2.33.3"
git2 = "0.13.19"
semver = "0.11.0"

